// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_celder20.Models;

namespace Mission6_celder20.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230221202206_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_celder20.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            AppId = 2,
                            CategoryId = 4,
                            Director = "Kenny Ortega",
                            Edited = false,
                            Rating = "PG",
                            Title = "High School Musical",
                            Year = 2006
                        },
                        new
                        {
                            AppId = 3,
                            CategoryId = 1,
                            Director = "Boaz Yakin",
                            Edited = false,
                            LentTo = "Jason Thompson",
                            Notes = "The best sports movie!",
                            Rating = "PG",
                            Title = "Remember the Titans",
                            Year = 2000
                        },
                        new
                        {
                            AppId = 4,
                            CategoryId = 2,
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014
                        });
                });

            modelBuilder.Entity("Mission6_celder20.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Suspense/Drama"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Action/Romance"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Romance-Comedy (Rom-Com)"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("Mission6_celder20.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Mission6_celder20.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
