// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_celder20.Models;

namespace Mission6_celder20.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230214054154_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_celder20.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            AppId = 2,
                            Category = "Musical",
                            Director = "Kenny Ortega",
                            Edited = false,
                            Rating = "PG",
                            Title = "High School Musical",
                            Year = 2006
                        },
                        new
                        {
                            AppId = 3,
                            Category = "Sports",
                            Director = "Boaz Yakin",
                            Edited = false,
                            LentTo = "Jason Thompson",
                            Notes = "The best sports movie!",
                            Rating = "PG",
                            Title = "Remember the Titans",
                            Year = 2000
                        },
                        new
                        {
                            AppId = 4,
                            Category = "Suspense/Drama",
                            Director = "Christopher Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
